### ISSUE TITLE
API discussion REST vs RPC

### ISSUE THREAD

**Issue by Gzing** [OriginProtocol/bridge-server#17]
Kicking the discussion off here:
Currently we have `apilib` which uses RPC style API's which might be useful for creating methods to do various actions which touch different resources from a single endpoint.
I don't feel the need at bridge server is to have method based endpoints since most of the resources are independent. for ex: indexing server only exposes read-only API's
Plus following REST would be very intuitive and easier for people to fork and onboard.

@matthewliu @tyleryasaka

**Comment by joshfraser** [comment]
Tagging @jlgoldman, the author of `apilib`

**Comment by UnicycleJonathan** [comment]
Totally up to you guys. I kind of hate REST even when used properly, and it prevents you from ever doing something RPC-style if you need it years down the line. That said, REST interfaces are the best understood by the community, and I'm not going to be the one working on this. From a purely detached perspective, you should probably use a publicly-documented API framework.

**Comment by tyleryasaka** [comment]
Yes I generally agree with everything that's been said here. In my opinion we should be using a well-documented, robust API library - one that is popular enough that there is a bit of a community around it. And it should be REST - I'm not too opinionated about REST one way or another but it is the norm right now. We should be doing as much as possible to make this easy to consume and easy for new developers to start working on. Let's not reinvent the wheel here.

**Comment by Gzing** [comment]
here are a few good maintained API extensions for Flask:
1. https://github.com/jfinkels/flask-restless
2. https://github.com/flask-restful/flask-restful
3. https://github.com/biosustain/potion

I had tried the first one and looked good, but is too opinionated about the way of doing things. Will evaluate these three and finalise one.

Open to any other suggestions.

**Comment by joshfraser** [comment]
Sounds like we have consensus around using https://github.com/jfinkels/flask-restless going forward.
