### ISSUE TITLE
Remove apilib and switch to a publicly maintained REST framework

### ISSUE THREAD

**Issue by Gzing** [OriginProtocol/bridge-server#21]

**Comment by joshfraser** [comment]
Sounds like we have consensus around using https://github.com/jfinkels/flask-restless.

**Comment by tyleryasaka** [comment]
So, from what I can tell, Flask Restless is for automatically generating API endpoints around database models. That won't be sufficient for our attestation endpoints. For creating our own custom endpoints, I think we should use [flask-restful](https://flask-restful.readthedocs.io/en/latest/api.html).

**Comment by tyleryasaka** [comment]
Finished by https://github.com/OriginProtocol/bridge-server/pull/28
