### ISSUE TITLE
Exceptions in attestation_service should raise specific exceptions 

### ISSUE THREAD

**Issue by crazybuster** [OriginProtocol/bridge-server#29]
Exceptions in the logic/attestation_service.py should raising different exceptions for each error case instead of a single generic one with different codes and messages. This way we can catch and handle specific exceptions if we want to, and also test those cases.

**Comment by ambertch** [comment]
This seems related to #33, I'll work on this as well.

**Comment by ambertch** [comment]
Taken care of by https://github.com/OriginProtocol/bridge-server/pull/48
