### ISSUE TITLE
Design and stub out identity service

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/bridge-server#3]
Come up with high-level identity requests and responses.

Needs to be able to handle at least three use cases:
- Proxy service for publicly auditable proofs
- Third-party attestation server
- Origin attestation server (really a subset of the above)

**Comment by tyleryasaka** [comment]
Attestation server is done by https://github.com/OriginProtocol/bridge-server/pull/28. We chose to move away from publicly-auditable proofs for now.
