### ISSUE TITLE
Better return types for attestation service

### ISSUE THREAD

**Issue by tyleryasaka** [OriginProtocol/bridge-server#33]
The attestation service is currently returning dictionaries - should probably return something more structured.

EDIT: This was created from `crazybuster`'s comment on this PR: https://github.com/OriginProtocol/bridge-server/pull/28

**Comment by ambertch** [comment]
Discussed with Tyler. 

I'd guess that when a data structure is returned in a similar format from many methods or places, it's good practice to encapsulate the data.

I'll open a PR for this issue.

**Comment by azban** [comment]
is there remaining work here now that #48 has been merged? @tyleryasaka @ambertch

**Comment by ambertch** [comment]
@azban I believe this one is completed.
