### ISSUE TITLE
Null columns in verification_code table

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/bridge-server#41]
verification_code is used for both email and phone numbers, and so one of the columns will be NULL. Some database people will say it is bad practice to allow null values.

**Comment by ambertch** [comment]
Is the main output of the identity service actually the signature? If so, this table is just used to store temporary codes and isn't a primary store of information.

**Comment by tyleryasaka** [comment]
@ambertch Correct, the database is just a temporary store for the validation process. The valuable output is the signature that is returned.
