### ISSUE TITLE
Create a better index page for the bridge server

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/bridge-server#59]
Visiting the root domain of our bridge server (
https://bridge.originprotocol.com) currently returns a plain text response.

We can do better than this.

An ideal solution would:

- Explain to visitors what the bridge server is, what functionality it provides (indexing, notifications and identity attestations), how it fits into our platform & the implications of using it (ie. select a bridge server you trust or host your own)
- Links to our bridge server repo and related docs 
- Look attractive and be on-brand with the rest of our design

**Comment by tyleryasaka** [comment]
This is completed by: https://github.com/OriginProtocol/bridge-server/pull/85

Thanks @mek32390 !
