### ISSUE TITLE
Celery worker crashes on start

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/bridge-server#71]
The current version of celery is set to 4.1.0 https://github.com/OriginProtocol/bridge-server/blob/develop/requirements.txt#L7

4.1.0 has a dependency (kombu >= 4.0.2) https://github.com/celery/celery/blob/v4.1.0/requirements/default.txt#L3

Yesterday, a new version of kombu (4.2.0) was uploaded to PyPi which has a code change that makes it incompatible with the bridge server's version of celery https://github.com/celery/kombu/blob/v4.2.0/Changelog#L47

4.2.0 https://github.com/celery/celery/blob/v4.2.0rc4/celery/worker/worker.py#L243
4.1.0 https://github.com/celery/celery/blob/v4.1.0/celery/worker/worker.py#L241

This means that new installs of the bridge server, when running the celery worker, will error out.

Solutions:
1. Add kombu==4.1.0 in requirements.txt
2. Wait for celery devs to update the version in PyPi and bump requirements.txt version to 4.2.0 (the version tagged in PyPi is currently 4.1.x, although 4.2 is currently at rc4 https://pypi.org/project/celery/#history)

**Comment by Gzing** [comment]
Closed by #73. Pinned Kombu to 4.1.0 for now. Will upgrade when Celery 4.2 is out.
