### ISSUE TITLE
Listing prices are stored in DB as an integer

### ISSUE THREAD

**Issue by ambertch** [OriginProtocol/bridge-server#75]
The price column of the Listing table is created as an int https://github.com/OriginProtocol/bridge-server/blob/master/database/migrations/versions/47df3d43171e_add_listing_table.py#L27

When listings get indexed, the prices get rounded:

<img width="1238" alt="screenshot 2018-05-24 16 12 44" src="https://user-images.githubusercontent.com/156263/40518117-c3e6f5da-5f6d-11e8-84af-b237aef19f37.png">

**Comment by micahalcorn** [comment]
Done via #77 ✅
