### ISSUE TITLE
Implement email address verification in identity service

### ISSUE THREAD

**Issue by matthewliu** [OriginProtocol/bridge-server#9]

**Comment by micahalcorn** [comment]
@tyleryasaka et al: from the UX perspective, email address verification usually involves receiving an email that contains a link, clicking that link, and the router doing something with a token contained in the URL. I assume that the plan is as follows:

1) DApp sends request to bridge server for a verification email to be generated
2) bridge server generates email
3) user clicks link in email
4) DApp* parses token
5) DApp* posts token to bridge server and stores the response in React state

Note that in step 4, this* is almost certainly **_a new and different tab/window_** than the one that initiated the verification. Assuming that the user may already have other unpublished identities or profile attributes in React state, they will be sitting with two different "sessions" that cannot be combined for a batched publication. So at a minimum, two transactions will be required to publish the changes. And most likely the user will abandon one of the two or get confused/frustrated.

Without local storage, how do we handle this email verification case?

**Comment by tyleryasaka** [comment]
@micahalcorn One solution is to just let the user copy/paste the code without ever having to navigate away from the page. The other solution that comes to mind is exactly what you mentioned, using local storage.

Either way, this sounds like a demo-dapp UI issue more than a bridge-server issue. Might be good to move this discussion over there.

**Comment by tyleryasaka** [comment]
Finished by https://github.com/OriginProtocol/bridge-server/pull/28
